### ISSUE TITLE
Stephen... O'Brien?

### ISSUE THREAD

**Issue by Qix-** [jessfraz/shaking-finger-action#1]
> A GitHub action that displays a gif of **Stephen Colbert** shaking his finger to a pull request on fail.

> ![](https://github.com/jessfraz/shaking-finger-action/raw/master/demo.png)

![](https://media1.giphy.com/media/ARH12W5IVAbni/giphy.gif?cid=3640f6095bf449e475705266457cfa77)

**Comment by jessfraz** [comment]
thanks fixed
